### ISSUE TITLE
ジャンル追加の可能性について

### ISSUE THREAD

**Issue by yuksaki72** [fujimondesu/2023Dev3Early#11]
開発中に追加したいジャンルが発生した場合に備えて、サーバーサイド設計書では消してしまったけど、ジャンルテーブルを読み込む処理を復活させようと思います。

**Comment by yuksaki72** [comment]
あ、ホーム画面を表示する時と話題新規作成画面でジャンルを選択する時です。

**Comment by fujimondesu** [comment]
ういす
