### ISSUE TITLE
ロゴ

### ISSUE THREAD

**Issue by nakashima0918** [fujimondesu/2023Dev3Early#5]
ロゴどーする？

**Comment by fujimondesu** [comment]
拝啓
　_石松様、ロゴの進捗はどうでしょうか。_
敬具

**Comment by yuksaki72** [comment]
**出来たら送って欲しい**

**Comment by fujimondesu** [comment]
@fujimondesu

**Comment by fujimondesu** [comment]
@ishimatuhub

**Comment by fujimondesu** [comment]
反応がございません！どうすれば...

**Comment by fujimondesu** [comment]
あああああああああぁっぁぁぁぁあｌっぁぁっぁぁぁぁぁぁっぁああぁぁぁぁっぁぁぁぁぁあぁぁぁぁぁ

**Comment by fujimondesu** [comment]
ウェーん

**Comment by fujimondesu** [comment]
@nakashima0918 
前の開発で作ったロゴどうやって作った？
サイトのURLあったらここに送ってほしい。

**Comment by fujimondesu** [comment]
１１４５１４

**Comment by nakashima0918** [comment]
アプリでつくって、インストーラー消したからない

**Comment by yuksaki72** [comment]
canvaってやつか
https://www.canva.com/ja_jp/download/windows/
Windowsはこっからダウンロード出来るかも

**Comment by nakashima0918** [comment]
WEBでもできたと思う

**Comment by nakashima0918** [comment]
一応作ったロゴteamsにあげてた
変えるかもしれんけど

**Comment by fujimondesu** [comment]
感謝感謝
