### ISSUE TITLE
ユーザー名の重複について

### ISSUE THREAD

**Issue by yuksaki72** [fujimondesu/2023Dev3Early#8]
ユーザー名の重複をありにしたいんやけど、どっちがいいか意見を聞きたいぜ
パスワード忘れたときのリセットする画面で、メールアドレスかユーザー名で本人を検索してて、これだとユーザー名が一意じゃないといけないんよね

**Comment by nakashima0918** [comment]
ユーザー名の重複を認めるんやったら、メールアドレスのみでいいんじゃね
てかユーザー名かぶるからできなそう

**Comment by nakashima0918** [comment]
偽物でてくる

**Comment by yuksaki72** [comment]
なしでいこう！！
